import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";
import type { PerformanceReport } from "@/server/reports/performance";
import type { SourceReport } from "@/server/reports/sources";
import type { PunctualityReport } from "@/server/reports/punctuality";
import type { RawReport } from "@/server/reports/raw";

/**
 * RP-01 — Excel and PDF export.
 *
 * THE SHAPE OF THIS FILE IS THE POINT. Four reports times two formats is eight
 * exporters if written directly, and eight places for a column to be renamed in
 * seven of them. Instead every report is first flattened into one neutral
 * `ExportDocument` (a title, some meta, and sections that are either a summary
 * block or a table), and there are exactly TWO renderers — one for .xlsx, one
 * for .pdf. Adding a report means adding a shaper, not touching either renderer.
 *
 * The numbers are never recomputed here. This module receives Dev A's report
 * payloads exactly as the screen received them, so an export cannot disagree
 * with the screen it was exported from — which is the whole reason we agreed a
 * contract before building.
 */

export const REPORT_KINDS = ["performance", "sources", "punctuality", "raw"] as const;
export type ReportKind = (typeof REPORT_KINDS)[number];

export const REPORT_TITLES: Record<ReportKind, string> = {
  performance: "Performance report",
  sources: "Lead source report",
  punctuality: "Punctuality report",
  raw: "Raw call data",
};

export interface ExportColumn {
  header: string;
  key: string;
  /** Relative weight: the PDF scales these to the page, Excel uses them as characters. */
  width: number;
  align?: "left" | "right";
}

export type ExportSection =
  | { type: "summary"; title: string; items: { label: string; value: string }[] }
  | {
      type: "table";
      title: string;
      columns: ExportColumn[];
      rows: Record<string, string | number | null>[];
      note?: string;
    };

export interface ExportDocument {
  title: string;
  /** Dev A's server-rendered range label, frozen at generation time. */
  subtitle: string;
  meta: { label: string; value: string }[];
  sections: ExportSection[];
}

export interface ExportContext {
  rangeLabel: string;
  generatedAt: Date;
  generatedBy: string;
  filters: { agent?: string | null; source?: string | null; disposition?: string | null };
}

// --- formatting -------------------------------------------------------------

/** 4210 -> "1h 10m 10s". A cell holding raw seconds is unreadable to a human. */
export function hms(totalSec: number): string {
  const s = Math.max(0, Math.round(totalSec));
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  if (h > 0) return `${h}h ${m}m ${sec}s`;
  if (m > 0) return `${m}m ${sec}s`;
  return `${sec}s`;
}

function pct(n: number): string {
  return `${n.toFixed(1)}%`;
}

function dateTime(iso: string): string {
  return new Date(iso).toLocaleString("en-GB", { dateStyle: "short", timeStyle: "short" });
}

function metaOf(ctx: ExportContext): { label: string; value: string }[] {
  return [
    { label: "Period", value: ctx.rangeLabel },
    { label: "Generated", value: ctx.generatedAt.toLocaleString("en-GB") },
    { label: "Generated by", value: ctx.generatedBy },
    { label: "Agent filter", value: ctx.filters.agent || "All agents" },
    { label: "Source filter", value: ctx.filters.source || "All sources" },
    { label: "Outcome filter", value: ctx.filters.disposition || "All outcomes" },
  ];
}

// --- shapers, one per report ------------------------------------------------

export function performanceDocument(r: PerformanceReport, ctx: ExportContext): ExportDocument {
  const outcomeRows = Object.entries(r.outcomes).map(([code, count]) => ({
    outcome: code === "undispositioned" ? "No outcome recorded" : code.replace(/_/g, " "),
    count,
    share: r.totals.callsMade > 0 ? pct((count / r.totals.callsMade) * 100) : "0.0%",
  }));

  return {
    title: REPORT_TITLES.performance,
    subtitle: ctx.rangeLabel,
    meta: metaOf(ctx),
    sections: [
      {
        type: "summary",
        title: "Totals",
        items: [
          { label: "Leads assigned", value: String(r.totals.leadsAssigned) },
          { label: "Leads worked", value: String(r.totals.leadsWorked) },
          { label: "Calls made", value: String(r.totals.callsMade) },
          { label: "Talk time", value: hms(r.totals.talkTimeSec) },
          { label: "Average talk time", value: hms(r.totals.avgTalkSec) },
          { label: "Callbacks set", value: String(r.totals.callbacksSet) },
          { label: "Callbacks completed", value: String(r.totals.callbacksDone) },
          { label: "Qualified", value: String(r.totals.qualified) },
          { label: "Conversion", value: pct(r.totals.conversionPct) },
        ],
      },
      {
        type: "table",
        title: "By agent",
        columns: [
          { header: "Agent", key: "fullName", width: 24 },
          { header: "Leads worked", key: "leadsWorked", width: 13, align: "right" },
          { header: "Calls", key: "calls", width: 9, align: "right" },
          { header: "Talk time", key: "talkTime", width: 13, align: "right" },
          { header: "Avg talk", key: "avgTalk", width: 11, align: "right" },
          { header: "Qualified", key: "qualified", width: 11, align: "right" },
          { header: "Conversion", key: "conversion", width: 12, align: "right" },
          { header: "Callbacks set", key: "callbacksSet", width: 13, align: "right" },
          { header: "Callbacks done", key: "callbacksDone", width: 14, align: "right" },
        ],
        rows: r.byAgent.map((a) => ({
          fullName: a.fullName,
          leadsWorked: a.leadsWorked,
          calls: a.calls,
          talkTime: hms(a.talkTimeSec),
          avgTalk: hms(a.avgTalkSec),
          qualified: a.qualified,
          conversion: pct(a.conversionPct),
          callbacksSet: a.callbacksSet,
          callbacksDone: a.callbacksDone,
        })),
        note: "Conversion is qualified divided by leads worked — a lead carrying an outcome, not a dialled attempt.",
      },
      {
        type: "table",
        title: "Outcome mix",
        columns: [
          { header: "Outcome", key: "outcome", width: 24 },
          { header: "Calls", key: "count", width: 10, align: "right" },
          { header: "Share of calls", key: "share", width: 14, align: "right" },
        ],
        rows: outcomeRows,
      },
      {
        type: "table",
        title: "By day",
        columns: [
          { header: "Date", key: "date", width: 14 },
          { header: "Calls", key: "calls", width: 10, align: "right" },
          { header: "Leads worked", key: "leadsWorked", width: 13, align: "right" },
          { header: "Qualified", key: "qualified", width: 11, align: "right" },
        ],
        rows: r.byDay.map((d) => ({ ...d })),
      },
    ],
  };
}

export function sourcesDocument(r: SourceReport, ctx: ExportContext): ExportDocument {
  const columns: ExportColumn[] = [
    { header: "Source", key: "source", width: 26 },
    { header: "Imported", key: "imported", width: 11, align: "right" },
    { header: "Owned now", key: "assigned", width: 12, align: "right" },
    { header: "Worked", key: "worked", width: 10, align: "right" },
    { header: "Contacted", key: "contacted", width: 11, align: "right" },
    { header: "Qualified", key: "qualified", width: 11, align: "right" },
    { header: "Do Not Call now", key: "doNotCall", width: 15, align: "right" },
    { header: "Worked %", key: "workedPct", width: 11, align: "right" },
    { header: "Conversion", key: "conversionPct", width: 12, align: "right" },
  ];

  const rows: Record<string, string | number | null>[] = r.sources.map((s) => ({
    source: s.source,
    imported: s.imported,
    assigned: s.assigned,
    worked: s.worked,
    contacted: s.contacted,
    qualified: s.qualified,
    doNotCall: s.doNotCall,
    workedPct: pct(s.workedPct),
    conversionPct: pct(s.conversionPct),
  }));

  rows.push({
    source: "TOTAL",
    imported: r.totals.imported,
    assigned: r.totals.assigned,
    worked: r.totals.worked,
    contacted: r.totals.contacted,
    qualified: r.totals.qualified,
    doNotCall: r.totals.doNotCall,
    workedPct: pct(r.totals.workedPct),
    conversionPct: pct(r.totals.conversionPct),
  });

  return {
    title: REPORT_TITLES.sources,
    subtitle: ctx.rangeLabel,
    meta: metaOf(ctx),
    sections: [
      {
        type: "table",
        title: "By source",
        columns,
        rows,
        note: "Imported, worked, contacted and qualified count what happened inside the period. Owned now and Do Not Call now are current state and do not move with the period; Owned now counts every lead that still has an agent attached, closed ones included. Conversion is qualified divided by worked, never by imported — a source with a large untouched backlog is unworked, not underperforming. Worked % compares work done in the period against leads imported in the same period.",
      },
    ],
  };
}

export function punctualityDocument(r: PunctualityReport, ctx: ExportContext): ExportDocument {
  return {
    title: REPORT_TITLES.punctuality,
    subtitle: ctx.rangeLabel,
    meta: [
      ...metaOf(ctx),
      { label: "Shift start", value: `${r.shift.startTime} (+${r.shift.graceMinutes} min grace)` },
    ],
    sections: [
      {
        type: "table",
        title: "Summary by agent",
        columns: [
          { header: "Agent", key: "fullName", width: 26 },
          { header: "Days present", key: "daysPresent", width: 13, align: "right" },
          { header: "Days late", key: "daysLate", width: 11, align: "right" },
          { header: "Late minutes", key: "totalLateMinutes", width: 13, align: "right" },
          { header: "On time", key: "onTimePct", width: 11, align: "right" },
        ],
        rows: r.summary.map((s) => ({
          fullName: s.fullName,
          daysPresent: s.daysPresent,
          daysLate: s.daysLate,
          totalLateMinutes: s.totalLateMinutes,
          onTimePct: pct(s.onTimePct),
        })),
        note: `Late means the first login of the day is past ${r.shift.startTime} plus the ${r.shift.graceMinutes}-minute grace period.`,
      },
      {
        type: "table",
        title: "Day by day",
        columns: [
          { header: "Date", key: "date", width: 13 },
          { header: "Agent", key: "fullName", width: 24 },
          { header: "First login", key: "firstLoginAt", width: 17 },
          { header: "Late (min)", key: "lateMinutes", width: 11, align: "right" },
          { header: "On time", key: "onTime", width: 10 },
          { header: "Sessions", key: "sessionCount", width: 10, align: "right" },
        ],
        rows: r.rows.map((row) => ({
          date: row.date,
          fullName: row.fullName,
          firstLoginAt: dateTime(row.firstLoginAt),
          lateMinutes: row.lateMinutes,
          onTime: row.onTime ? "Yes" : "No",
          sessionCount: row.sessionCount,
        })),
      },
    ],
  };
}

export function rawDocument(r: RawReport, ctx: ExportContext): ExportDocument {
  return {
    title: REPORT_TITLES.raw,
    subtitle: ctx.rangeLabel,
    meta: [...metaOf(ctx), { label: "Rows", value: `${r.rows.length} of ${r.total}` }],
    sections: [
      {
        type: "table",
        title: "Calls",
        columns: [
          { header: "When", key: "at", width: 16 },
          { header: "Agent", key: "agent", width: 18 },
          { header: "Company", key: "company", width: 22 },
          { header: "Contact", key: "contact", width: 18 },
          { header: "Phone", key: "phone", width: 16 },
          { header: "Source", key: "source", width: 18 },
          { header: "Outcome", key: "outcome", width: 18 },
          { header: "Duration", key: "duration", width: 11, align: "right" },
          { header: "Channel", key: "channel", width: 11 },
          { header: "Callback", key: "callbackAt", width: 16 },
          { header: "Notes", key: "notes", width: 40 },
        ],
        rows: r.rows.map((row) => ({
          at: dateTime(row.at),
          agent: row.agent,
          company: row.company,
          contact: row.contact,
          phone: row.phone,
          source: row.source,
          outcome: row.outcome ?? "No outcome recorded",
          duration: row.durationSec === null ? "—" : hms(row.durationSec),
          channel: row.channel,
          callbackAt: row.callbackAt ? dateTime(row.callbackAt) : "",
          notes: row.notes,
        })),
        note: "A blank duration is a MANUAL row — an outcome recorded without dialling, which carries no duration by design.",
      },
    ],
  };
}

// --- renderers --------------------------------------------------------------

export async function toXlsx(doc: ExportDocument): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.created = new Date();

  const cover = wb.addWorksheet("Report");
  cover.columns = [{ width: 24 }, { width: 60 }];
  cover.addRow([doc.title]).font = { bold: true, size: 16 };
  cover.addRow([doc.subtitle]).font = { size: 12, color: { argb: "FF555555" } };
  cover.addRow([]);
  for (const m of doc.meta) {
    const row = cover.addRow([m.label, m.value]);
    row.getCell(1).font = { bold: true };
  }

  for (const section of doc.sections) {
    if (section.type === "summary") {
      cover.addRow([]);
      cover.addRow([section.title]).font = { bold: true, size: 13 };
      for (const item of section.items) {
        const row = cover.addRow([item.label, item.value]);
        row.getCell(1).font = { bold: true };
      }
      continue;
    }

    // Excel sheet names cannot exceed 31 characters or contain : \ / ? * [ ]
    const name = section.title.replace(/[:\\/?*[\]]/g, " ").slice(0, 31);
    const ws = wb.addWorksheet(name);
    ws.columns = section.columns.map((c) => ({ header: c.header, key: c.key, width: c.width }));
    ws.getRow(1).font = { bold: true };
    ws.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFEFEFEF" } };
    ws.views = [{ state: "frozen", ySplit: 1 }];
    ws.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: 1, column: section.columns.length },
    };

    for (const row of section.rows) {
      ws.addRow(row);
    }
    for (const [i, c] of section.columns.entries()) {
      if (c.align === "right") ws.getColumn(i + 1).alignment = { horizontal: "right" };
    }
    if (section.note) {
      ws.addRow([]);
      ws.addRow([section.note]).font = { italic: true, color: { argb: "FF555555" } };
    }
  }

  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf);
}

const PDF_MARGIN = 32;
const ROW_HEIGHT = 13;

export function toPdf(doc: ExportDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    // Landscape because every one of these reports is a wide table; portrait
    // forces either a microscopic font or a column off the page.
    const pdf = new PDFDocument({ size: "A4", layout: "landscape", margin: PDF_MARGIN });
    const chunks: Buffer[] = [];
    pdf.on("data", (c: Buffer) => chunks.push(c));
    pdf.on("end", () => resolve(Buffer.concat(chunks)));
    pdf.on("error", reject);

    const pageWidth = pdf.page.width - PDF_MARGIN * 2;
    const bottom = pdf.page.height - PDF_MARGIN;

    pdf.font("Helvetica-Bold").fontSize(18).fillColor("#111111").text(doc.title);
    pdf.moveDown(0.2);
    pdf.font("Helvetica").fontSize(11).fillColor("#555555").text(doc.subtitle);
    pdf.moveDown(0.6);

    pdf.fontSize(8).fillColor("#444444");
    pdf.text(doc.meta.map((m) => `${m.label}: ${m.value}`).join("    |    "), { width: pageWidth });
    pdf.moveDown(0.8);

    const drawHeader = (columns: ExportColumn[], xs: number[], widths: number[]) => {
      const y = pdf.y;
      pdf.rect(PDF_MARGIN, y - 2, pageWidth, 16).fill("#EFEFEF");
      pdf.fillColor("#111111").font("Helvetica-Bold").fontSize(8);
      columns.forEach((c, i) => {
        pdf.text(c.header, xs[i], y + 2, {
          width: widths[i] - 4,
          align: c.align ?? "left",
          lineBreak: false,
          ellipsis: true,
        });
      });
      pdf.y = y + 16;
    };

    for (const section of doc.sections) {
      if (pdf.y > bottom - 80) pdf.addPage();

      pdf.font("Helvetica-Bold").fontSize(12).fillColor("#111111").text(section.title, PDF_MARGIN, pdf.y);
      pdf.moveDown(0.3);

      if (section.type === "summary") {
        const half = Math.ceil(section.items.length / 2);
        const colWidth = pageWidth / 2;
        const top = pdf.y;
        pdf.fontSize(9).fillColor("#222222");
        section.items.forEach((item, i) => {
          const col = i < half ? 0 : 1;
          const rowIndex = i < half ? i : i - half;
          const y = top + rowIndex * 14;
          pdf.font("Helvetica").text(item.label, PDF_MARGIN + col * colWidth, y, {
            width: colWidth * 0.6,
            lineBreak: false,
            ellipsis: true,
          });
          pdf
            .font("Helvetica-Bold")
            .text(item.value, PDF_MARGIN + col * colWidth + colWidth * 0.6, y, {
              width: colWidth * 0.35,
              lineBreak: false,
              ellipsis: true,
            });
        });
        pdf.y = top + half * 14 + 10;
        continue;
      }

      const totalWeight = section.columns.reduce((sum, c) => sum + c.width, 0);
      const widths = section.columns.map((c) => (c.width / totalWeight) * pageWidth);
      const xs: number[] = [];
      let x = PDF_MARGIN;
      for (const w of widths) {
        xs.push(x);
        x += w;
      }

      drawHeader(section.columns, xs, widths);
      pdf.font("Helvetica").fontSize(8).fillColor("#222222");

      section.rows.forEach((row, index) => {
        if (pdf.y > bottom - 24) {
          pdf.addPage();
          drawHeader(section.columns, xs, widths);
          pdf.font("Helvetica").fontSize(8).fillColor("#222222");
        }
        const y = pdf.y;
        if (index % 2 === 1) {
          pdf.rect(PDF_MARGIN, y - 2, pageWidth, ROW_HEIGHT).fill("#F7F7F7");
          pdf.fillColor("#222222");
        }
        section.columns.forEach((c, i) => {
          const value = row[c.key];
          pdf.text(value === null || value === undefined ? "" : String(value), xs[i], y, {
            width: widths[i] - 4,
            align: c.align ?? "left",
            lineBreak: false,
            ellipsis: true,
          });
        });
        pdf.y = y + ROW_HEIGHT;
      });

      if (section.note) {
        pdf.moveDown(0.4);
        pdf
          .font("Helvetica-Oblique")
          .fontSize(7)
          .fillColor("#666666")
          .text(section.note, PDF_MARGIN, pdf.y, { width: pageWidth });
        pdf.fillColor("#222222");
      }
      pdf.moveDown(0.8);
    }

    pdf.end();
  });
}

export const MIME: Record<"XLSX" | "PDF", string> = {
  XLSX: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  PDF: "application/pdf",
};

export const EXTENSION: Record<"XLSX" | "PDF", string> = { XLSX: ".xlsx", PDF: ".pdf" };
